### ISSUE TITLE
Code Question

### ISSUE THREAD

**Issue by ProgrammerZhujinming** [penway/LFM#1]
Hi, I have a question about the code in line 226 of file LFMz.py, why do you use the formulation n2[z_dim-1] = -dr / n1[z_dim-1] ranther  than jude the result about abs(dr) <= esp (such as 1e-5), please reply to me at your convenience. Thank you!

**Comment by penway** [comment]
I am sorry I don't fully understand the reason you proposed the new formulation, but if you mean directly judge if the dot product is closed enough to be perpendicular, my original thought was just to ensure these two vectors are orthogonal to each other by directly change the last element of vector n2. As two random generated vectors are not likely to have a 0 dot product.
However, my method is indeed a pretty clumsy way, so if you have a better idea please enlighen me.

**Comment by penway** [comment]
I am sorry I don't fully understand the reason you proposed the new formulation, but if you mean directly judge if the dot product is closed enough to be perpendicular, my original thought was just to ensure these two vectors are orthogonal to each other by directly change the last element of vector n2. As two random generated vectors are not likely to have a 0 dot product.
However, my method is indeed a pretty clumsy way, so if you have a better idea please enlighen me.

**Comment by ProgrammerZhujinming** [comment]
Oh, you are too modest, I think your thought is very enlightening. Like you, I hold the view that two random generated vectors are not likely to have a 0 dot product. Maybe my concern is whether changing the last element of vector n2 is harmful to the distribution of vector n2. I'm not sure. It's just a bit of my own folly. However, if we simply sample two random generated vectors and anticipate  the dot product is closed enough to be perpendicular, it consumes resources very much.
I really appreciate your reply!

**Comment by penway** [comment]
Yes, I assume the consumption of resources is unacceptable. While having the concern of harming the distribution, I have a little trick in line 227 which is `if abs(n2[z_dim-1]) > 1.5: continue`, to make it less likely to generate drastic result. However, this still damage the distribution and cost about half of the generation been thrown. But I have not come up with a better algorithm.
I will close the issue here and if you have any new idea about it, feel free to open it up.
